theme: jekyll-theme-minimal
# Site Settings
locale                   : "ja-JP"  
title                    : "KTR-1 WEB教材"
description              : "KTR-1のWEB教材です。"
logo                     : https://raw.githubusercontent.com/bit-trade-one/ADCRKTR1-KTR-1/master/docs/assets/img/logo.png
